### ISSUE TITLE
Meeting Minutes 

### ISSUE THREAD

**Issue by ChuckHo777** [UBC-MDS/simpler_eda#1]
- Came up with team contract 
- Decided on the project topic:
- Simple EDA 
	i.	Correlation maps (input: features to be correlated; output: correlation maps)  - Chuck
	ii.	Exploratory Plots for numerical features( input: x, y, color/fill, title, size of text, color; output: altair/matplot objects (e.g. Scatter plots))   - Deepak
	iii.	Exploratory Plots for categorical features (input: x, y, color/fill, title, size of text, color; output: altair/matplot objects (e.g. histogram or bar charts)   - Nick
- Creating the project structure with cookiecutter and poetry  - Nick
- Updating the documents: contributor.md, conduct.md, contributing.md  - Chuck
- Manage project task via GitHub Project and Issues
- Don't need to fork the repo, but branch out for each task

Next Meeting: February 25, 2021 at 7 p.m.

**Comment by nichowu** [comment]
google doc link to team contract 
[https://docs.google.com/document/d/1rirPyw0br-bLzHrMu_FvFWfD2KojmIfpD-HE2Gk_ntc/edit?usp=sharing](https://docs.google.com/document/d/1rirPyw0br-bLzHrMu_FvFWfD2KojmIfpD-HE2Gk_ntc/edit?usp=sharing)

**Comment by ChuckHo777** [comment]
Great teamwork!
