### ISSUE TITLE
Task: Editing the Project Documents: contributor.md, conduct.md, contributing.md

### ISSUE THREAD

**Issue by ChuckHo777** [UBC-MDS/simpler_eda#3]
Edit the project documents tailor to our project

**Comment by deepaksidhu** [comment]
Any idea on whether we are updating the .rst files for this? or changing them to .md files?

**Comment by ChuckHo777** [comment]
> Any idea on whether we are updating the .rst files for this? or changing them to .md files?

I think we can do either of them, but not sure whether it would affect the proccess for poetry publishing.  Let's check out with Tiffany or TA.

**Comment by deepaksidhu** [comment]
Yes, I think the issue will be on the poetry publishing. If we use rst it will be publish with all our other files as well.

**Comment by ChuckHo777** [comment]
We need to keep rst file as rst; otherwise, it will affect the python package workflow such as documentation and publishing.

The update is now completed.
